extends Node2D
##
## The field renderer: terrain in `_draw` (static, redrawn only when the map
## changes) and everything that moves in two MultiMeshes.
##
## 500 actors is past the point where a Node2D each is sensible — that is 500
## canvas items to cull, sort and batch every frame. One MultiMesh is one draw
## call, and the per-instance cost is three setter calls.
##
## Actors are soldiers off a sprite sheet: `assets/soldiers.png`, five poses in
## a row, generated by `scripts/sprites.gd` and committed. The pose index rides
## in the instance's custom data and `ui/actors.gdshader` turns it into a UV
## offset, so five poses still cost one MultiMesh and one draw call. Facing
## comes free with the instance transform, as it did with the chevron.
##
## The second MultiMesh carries bullets *and* muzzle flashes — same quad, a
## different scale and colour — because the budget is two and a flash is not
## worth a third.
##

const D := preload("res://scripts/data.gd")
const ACTOR_R := 6.0
## Half-extent of a sheet cell, in logical units. Must match `sprites.gd`.
const CELL_R := ACTOR_R * 2.6

const POSE_STAND := 0.0
const POSE_CROUCH := 1.0
const POSE_LUNGE := 2.0
const POSE_RAGDOLL := 3.0
const POSE_CORPSE := 4.0
## Ticks a body reads as freshly killed before it settles into a corpse.
const RAGDOLL_TICKS := 30
## Ticks after a shot that the muzzle is still flashing.
const FLASH_TICKS := 3
## Ticks after a melee swing that the actor is still lunging.
const LUNGE_TICKS := 10
const MELEE_COOLDOWN := 26

const TEAM_COLOR := [Color(0.35, 0.66, 1.0), Color(1.0, 0.48, 0.42)]
const CORPSE_COLOR := Color(0.30, 0.32, 0.38, 0.9)
const BULLET_COLOR := Color(1.0, 0.93, 0.66, 0.95)
const FLASH_COLOR := [Color(1.0, 0.88, 0.62, 0.95), Color(0.78, 0.98, 1.0, 0.95)]
const COVER_FILL := Color(0.137, 0.165, 0.22)
const COVER_BAG := [Color(0.20, 0.239, 0.318), Color(0.169, 0.204, 0.267)]
const COVER_TOP := Color(0.275, 0.325, 0.427)
const COVER_FOOT := Color(0.102, 0.125, 0.161)
const FIELD_FILL := Color(0.075, 0.083, 0.105)
const SPAWN_TINT := [Color(0.35, 0.66, 1.0, 0.05), Color(1.0, 0.48, 0.42, 0.05)]
## Nominal sandbag width along a face, in logical units.
const BAG := 13.0

var cover: PackedFloat64Array = PackedFloat64Array()

var _actors: MultiMeshInstance2D
var _bullets: MultiMeshInstance2D
var _am: MultiMesh
var _bm: MultiMesh
## Per-unit shade, so a unit reads as a block rather than as loose dots.
var _unit_color: PackedColorArray = PackedColorArray()
var _custom := Color(0, 0, 0, 0)


func _ready() -> void:
	_actors = MultiMeshInstance2D.new()
	_am = MultiMesh.new()
	_am.transform_format = MultiMesh.TRANSFORM_2D
	_am.use_colors = true
	_am.use_custom_data = true
	_am.mesh = _sprite_mesh(CELL_R)
	_actors.multimesh = _am
	_actors.texture = load("res://assets/soldiers.png")
	var mat := ShaderMaterial.new()
	mat.shader = load("res://ui/actors.gdshader")
	_actors.material = mat
	add_child(_actors)

	_bullets = MultiMeshInstance2D.new()
	_bm = MultiMesh.new()
	_bm.transform_format = MultiMesh.TRANSFORM_2D
	_bm.use_colors = true
	_bm.mesh = _quad_mesh(2.6, 1.4)
	_bullets.multimesh = _bm
	add_child(_bullets)


## A unit quad with UVs, `r` logical units from the centre to each edge.
static func _sprite_mesh(r: float) -> ArrayMesh:
	var verts := PackedVector3Array([
		Vector3(-r, -r, 0), Vector3(r, -r, 0), Vector3(r, r, 0),
		Vector3(-r, -r, 0), Vector3(r, r, 0), Vector3(-r, r, 0),
	])
	var uvs := PackedVector2Array([
		Vector2(0, 0), Vector2(1, 0), Vector2(1, 1),
		Vector2(0, 0), Vector2(1, 1), Vector2(0, 1),
	])
	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_TEX_UV] = uvs
	var m := ArrayMesh.new()
	m.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return m


static func _quad_mesh(w: float, h: float) -> ArrayMesh:
	var verts := PackedVector3Array([
		Vector3(-w, -h, 0), Vector3(w, -h, 0), Vector3(w, h, 0),
		Vector3(-w, -h, 0), Vector3(w, h, 0), Vector3(-w, h, 0),
	])
	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	var m := ArrayMesh.new()
	m.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return m


## Called when the world is replaced: resize the instance buffers and work out
## each unit's shade once.
func bind(world: RefCounted) -> void:
	cover = world.cover
	_unit_color.resize(world.n_units)
	var per_team := [0, 0]
	var count_team := [0, 0]
	for u in range(world.n_units):
		count_team[world.u_team[u]] += 1
	for u in range(world.n_units):
		var team: int = world.u_team[u]
		var n: int = maxi(count_team[team], 1)
		var k: float = float(per_team[team]) / float(n)
		per_team[team] += 1
		_unit_color[u] = TEAM_COLOR[team].lerp(Color(1, 1, 1), k * 0.45)
	_am.instance_count = world.n_actors
	_bm.instance_count = maxi(world.n_actors * 2, 64)
	queue_redraw()


func sync(world: RefCounted) -> void:
	var tick: int = world.tick
	for id in range(world.n_actors):
		var alive: bool = world.a_alive[id] == 1
		var pose := POSE_STAND
		var col: Color = _unit_color[world.a_unit[id]]
		if not alive:
			var fresh: bool = tick - world.a_death_tick[id] < RAGDOLL_TICKS
			pose = POSE_RAGDOLL if fresh else POSE_CORPSE
			# a body is still the colour of its side for a moment, then it is
			# just a body — which is also what stops a long battle's field of
			# dead from shouting louder than the men still on it
			col = col * 0.55 if fresh else CORPSE_COLOR
		elif world.a_melee_cd[id] > MELEE_COOLDOWN - LUNGE_TICKS:
			pose = POSE_LUNGE
		elif world.a_covered[id] == 1:
			pose = POSE_CROUCH
		_am.set_instance_transform_2d(id, Transform2D(world.a_facing[id], Vector2(world.ax[id], world.ay[id])))
		_am.set_instance_color(id, col)
		_custom.r = pose
		_am.set_instance_custom_data(id, _custom)

	var cap: int = _bm.instance_count
	var n: int = mini(world.b_count, cap)
	for i in range(n):
		var v := Vector2(world.b_vx[i], world.b_vy[i])
		_bm.set_instance_transform_2d(i, Transform2D(v.angle(), Vector2(world.b_x[i], world.b_y[i])))
		_bm.set_instance_color(i, BULLET_COLOR)
	# muzzle flashes share this MultiMesh: same quad, scaled up, warm. Derived
	# from the weapon cooldown, so the simulation owns no rendering state — an
	# actor whose cooldown is still within FLASH_TICKS of its weapon's full
	# value has just fired.
	var f := n
	for id in range(world.n_actors):
		if f >= cap:
			break
		if world.a_alive[id] == 0:
			continue
		var u: int = world.a_unit[id]
		if world.a_cooldown[id] < world.u_w_cooldown[u] - FLASH_TICKS:
			continue
		var ang: float = world.a_facing[id]
		var at := Vector2(world.ax[id], world.ay[id]) + Vector2(cos(ang), sin(ang)) * (ACTOR_R * 2.1)
		_bm.set_instance_transform_2d(f, Transform2D(ang, Vector2(1.7, 1.2), 0.0, at))
		_bm.set_instance_color(f, FLASH_COLOR[world.a_team[id]])
		f += 1
	_bm.visible_instance_count = f


func _draw() -> void:
	draw_rect(Rect2(0, 0, D.FIELD_W, D.FIELD_H), FIELD_FILL)
	draw_rect(D.SPAWN_A, SPAWN_TINT[0])
	draw_rect(D.SPAWN_B, SPAWN_TINT[1])
	var i := 0
	while i < cover.size():
		_draw_cover(Rect2(cover[i], cover[i + 1], cover[i + 2], cover[i + 3]))
		i += 4
	draw_rect(Rect2(0, 0, D.FIELD_W, D.FIELD_H), Color(0.22, 0.25, 0.31), false, 2.0)


##
## A sandbag emplacement rather than a grey box: a slab, a run of bags along
## each face, a lit top edge and a shadowed bottom one, so the wall reads as
## having a height instead of being a hole in the floor. The canvas build draws
## the same thing with the same numbers.
##
func _draw_cover(r: Rect2) -> void:
	draw_rect(r, COVER_FILL)
	for face in range(4):
		var horizontal := face < 2
		var span: float = r.size.x if horizontal else r.size.y
		var n := maxi(2, int(round(span / BAG)))
		var step := span / float(n)
		for k in range(n):
			var t: float = (r.position.x if horizontal else r.position.y) + (float(k) + 0.5) * step
			var c: Vector2
			var rad: Vector2
			if horizontal:
				c = Vector2(t, r.position.y if face == 0 else r.position.y + r.size.y)
				rad = Vector2(step * 0.56, 6.5)
			else:
				c = Vector2(r.position.x if face == 2 else r.position.x + r.size.x, t)
				rad = Vector2(6.5, step * 0.56)
			# draw_circle scaled by a transform would need a matrix push per
			# bag; an ellipse is two triangles' worth of polygon and costs less
			draw_colored_polygon(_ellipse_points(c, rad), COVER_BAG[k % 2])
	draw_line(Vector2(r.position.x, r.position.y - 1.0),
		Vector2(r.position.x + r.size.x, r.position.y - 1.0), COVER_TOP, 2.0)
	draw_line(Vector2(r.position.x, r.position.y + r.size.y + 1.0),
		Vector2(r.position.x + r.size.x, r.position.y + r.size.y + 1.0), COVER_FOOT, 1.6)


static func _ellipse_points(c: Vector2, rad: Vector2, steps: int = 12) -> PackedVector2Array:
	var pts := PackedVector2Array()
	pts.resize(steps)
	for i in range(steps):
		var a := TAU * float(i) / float(steps)
		pts[i] = Vector2(c.x + cos(a) * rad.x, c.y + sin(a) * rad.y)
	return pts
